# Generated by Django 4.2.1 on 2024-08-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0007_tagpost_alter_women_cat_women_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='women',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='women.tagpost'),
        ),
    ]
