# Generated by Django 5.1 on 2024-08-22 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0013_alter_category_slug_alter_women_cat_alter_women_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='women',
            options={
                'ordering': ['-time_create'],
                'verbose_name': 'Известная женщина',
                'verbose_name_plural': 'Известные женщины',
            },
        ),
    ]
